config/routes.rb
Rails.application.routes.draw do
  root to: "municipes#index"
  resources :enderecos
  resources :municipes, :except => [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  require "cpf_cnpj"
  validates :nome, :cpf, :cns, :email, :data_nascimento, :telefone, :foto, :status, :presence => true

  validate :verify_cpf
  validate :verify_cns
  validate :verify_date

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
  has_one :endereco

  has_one_attached :foto

  def verify_cpf
    if cpf.present?
      errors.add(:base, 'Cpf informado é inválido. Favor verificar e informar um cpf válido') if !CPF.valid?(cpf)
    end  
  end
  
  def verify_cns
    if cns.present?
      errors.add(:base, 'Cns informado é inválido. Favor verificar e informar um cns válido') if !validator_cns(cns)
    end  
  end

  def validator_cns(cns)
    begin
      soma = cns[0].to_i*15 + cns[1].to_i*14 + cns[2].to_i*13 + cns[3].to_i*12 + cns[4].to_i*11 + cns[5].to_i*10 + cns[6].to_i*9 + cns[7].to_i*8 + cns[8].to_i*7 + cns[9].to_i*6 + cns[10].to_i*5 + cns[11].to_i*4 + cns[12].to_i*3 + cns[13].to_i*2 + cns[14].to_i*1
      resto = soma % 11
      if resto != 0
        value = false
      else
        value = true  
      end         
    rescue 
      value = false
    end    
    value
  end  

  def verify_date
    if data_nascimento.present?
     begin
      Date.parse("'#{data_nascimento}'")
     rescue ArgumentError
      errors.add(:base, 'Data de Nascimento informada é inválido. Favor verificar e informar uma data válida')
     end
    end  
  end 

end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update ]

  # GET /municipes or /municipes.json
  def index
    @result = params["/municipe/index"].present? ? query_string(params["/municipe/index"]) : ''
    @municipes = Municipe.joins(:endereco).where(@result).paginate(page: params[:page], per_page: 20).order("id desc")
  end

  def query_string(params)
    result = []
    result << "nome ilike '%#{params[:nome]}%'" if params[:nome].present?
    result << "cpf ilike '%#{params[:cpf]}%'" if params[:cpf].present?
    result << "enderecos.cep ilike '%#{params[:cep]}%'" if params[:cep].present?
    result << "enderecos.codigo_ibge ilike '%#{params[:codigo_ibge]}%'" if params[:codigo_ibge].present?
    result = result.join(" AND ")
  end  

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    params[:municipe][:cpf] = params[:municipe][:cpf].gsub(/[.\/-]/, '')
    params[:municipe][:telefone] = params[:municipe][:telefone].gsub!(/[^0-9A-Za-z]/, '')
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if (params.keys.include?("municipe")) or (params.keys.include?("endereco")) and @municipe.save
        params[:endereco][:municipe_id] = @municipe.id
        @endereco = Endereco.new(endereco_params)
        if (params.keys.include?("endereco"))
          @endereco.save
        end
        @body_email = [@municipe, 'Cadastro']
        UserMailer.body_register_municipe(@body_email).deliver
        send_sms(@municipe, 'o', 'o cadastro')
        format.html { redirect_to municipe_url(@municipe), notice: "Municipio registrado com sucesso." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    @endereco = Endereco.find_by_municipe_id(@municipe.id)
    params[:endereco][:municipe_id] = @municipe.id
    params[:municipe][:cpf] = params[:municipe][:cpf].gsub(/[.\/-]/, '')
    params[:municipe][:telefone] = params[:municipe][:telefone].gsub!(/[^0-9A-Za-z]/, '')

    respond_to do |format|
      if @municipe.update(municipe_params)
        if (params.keys.include?("endereco"))
          if @endereco.present?
            @endereco.update(endereco_params)
            notice = 'Endereço atualizado com sucesso.'
          else
            @endereco = Endereco.new(endereco_params)
            @endereco.save
            notice = 'Endereço salvo com sucesso.'
          end
        end
        @body_email = [@municipe, 'Atualização']
        UserMailer.body_register_municipe(@body_email).deliver
        #send_sms(@municipe, 'a', 'a atualização')
        format.html { redirect_to municipe_url(@municipe), notice: "Municipio atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
      @endereco = Endereco.find_by_municipe_id(@municipe.id)
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      if params[:municipe].present?
        params.require(:municipe).permit(:nome, :cpf, :cns, :email, :data_nascimento, :telefone, :foto, :status)
      elsif params[:endereco].present?  
        params.require(:endereco).permit(:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :codigo_ibge, :municipe_id)
      end
    end

    def endereco_params
      params.require(:endereco).permit(:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :codigo_ibge, :municipe_id)
    end

    def sms_authenticate
      client = Vonage::Client.new(
        api_key: ENV['API_KEY'],
        api_secret: ENV['API_SECRET']
      )
    end  

    def send_sms(municipe, context, origin)
      sms_authenticate.sms.send(
        from: "Municipes System",
        to: municipe.telefone, #'5585988761897',
        text: body_sms(municipe, context, origin)
      )
    end  

    def body_sms(municipe, context, origin)
      msg = ""
      msg << "Foi realizad#{context} #{origin} do Municipe #{municipe.nome} com os seguinte dados: "
      msg << "CPF: #{municipe.cpf}, CNS: #{municipe.cns}, Telefone: #{municipe.telefone} e Status: #{municipe.status ? "Ativo" : "Inativo"} no dia "
      msg << "#{municipe.created_at.strftime("%d/%m/%Y")} ás #{municipe.created_at.strftime("%H:%M:%S")}"
    end  

    # def sanitizer_params(params)
    #   if params.present? 
    #     cpf = params[:municipe][:cpf].gsub(".") if params[:municipe][:cpf].present?
    #     cns = params[:municipe][:cns] if params[:municipe][:cns].present?
    #   end  
    # end  

end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/municipes/_filters.html.erb
<div class="card card-default">
  <div class="card-header">
    <h3 class="card-title">Consulta</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= form_for('/municipe/index', method: :get) do |form| %>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= form.label :nome %>
                  <% value_nome = params["/municipe/index"][:nome] rescue '' %>
                  <%= form.text_field :nome, class:"form-control", placeholder:"Informe o nome do Municipe", value: value_nome %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <%= form.label :cpf, "Cpf" %>
                  <% value_cpf = params["/municipe/index"][:cpf] rescue '' %>
                  <%= form.text_field :cpf, class:"form-control",  placeholder:"Informe o cpf", value: value_cpf %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= form.label :cep %>
                  <% value_cep = params["/municipe/index"][:cep] rescue '' %>
                  <%= form.text_field :cep, class:"form-control", placeholder:"Informe o cep", value: value_cep %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <%= form.label :codigo_ibge %>
                  <% value_codigo_ibge = params["/municipe/index"][:codigo_ibge] rescue '' %>
                  <%= form.text_field :cpf, class:"form-control",  placeholder:"Informe o código ibge", value: value_codigo_ibge %>
                </div>
              </div>
            </div>
            <div>
              <button type="submit" class="btn btn-primary">Consultar</button>
              <%= link_to 'Limpar', municipes_path, class:'btn btn-success', type:"button" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->

app/views/municipes/_form.html.erb
<%= form_with(model: municipe, html: { data: { controller: "masks" } }) do |form| %>
  <%= render "/municipes/partials/municipe", form: form, required: required, disabled: disabled %>
  <%= render "/municipes/partials/endereco", form: form, required: required, readonly: readonly, disabled: disabled %>
<% end %>  

app/views/municipes/_municipe.html.erb
<div id="<%= dom_id municipe %>">
  <p>
    <strong>Nome:</strong>
    <%= municipe.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= municipe.cpf %>
  </p>

  <p>
    <strong>Cns:</strong>
    <%= municipe.cns %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= municipe.email %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= municipe.data_nascimento %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= municipe.telefone %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= municipe.foto %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= municipe.status %>
  </p>

</div>

app/views/municipes/edit.html.erb
<%= render "form", municipe: @municipe, required: false, disabled: false, readonly: true %>

app/views/municipes/index.html.erb
<%= render "municipes/filters" %>

<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h2>Lista de Municipios</h2>

<div class="card card-default">
  <div class="card-header">
    <div class="d-flex justify-content-between">
      <div>
      </div>
      <div>
        <%= link_to 'Novo', new_municipe_path, class:'btn btn-success', type:"button" %>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nome</th>
          <th scope="col">CPF</th>
          <th scope="col">CNS</th>
          <th scope="col">Foto</th>
          <th scope="col">Status</th>
          <th scope="col" colspan="3">Ações</th>
        </tr>
      </thead>
      <tbody>
          <% @municipes.each do |municipe| %>
          <tr>
            <th scope="row"><%= municipe.id %></th>
            <th><%= municipe.nome %></th>
            <td><%= municipe.cpf %></td>
            <td><%= municipe.cns %></td>
            <td>
              <% if municipe.foto.attached? %>
                <%= image_tag url_for(municipe.foto), style: 'height:20px;width:120px;' %>
              <% end %>  
            </td>
            <td><%= municipe.status ? "Ativo" : "Inativo" %></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
              <%= link_to municipe do %>
                <i class="fa fa-eye" aria-hidden="true"></i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_municipe_path(municipe) do %>
                <i class="fa fa-edit" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero">
  <ul class="pagination">
    <li class="disabled"> <%= will_paginate(@articles,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0) %></li>
  </ul>
</div>

app/views/municipes/new.html.erb
<%= render "form", municipe: @municipe, required: false, disabled: false, readonly: true %>

app/views/municipes/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<%= form_with(model: @municipe, html: { data: { controller: "masks" } }) do |form| %>
  <%= render "/municipes/partials/municipe", form: form, required: false, disabled: true %>
  <%= render "/municipes/partials/endereco", form: form, required: true, readonly: true, disabled: true %>
<% end %>  

            